title: Kshitij Mishra
description: AI Quality Analyst | LLM Evaluation | Data Analyst | Prompt Engineer
url: "https://kshitij.info"
baseurl: ""
future: true
author:
  name: Kshitij Mishra
  email: mkshitij007@gmail.com
permalink: /:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor
